services:
  - type: web
    name: mood-music-app
    env: python
    buildCommand: "apt-get update && apt-get install -y libportaudio2 libportaudiocpp0 portaudio19-dev && pip install -r requirements.txt"
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
